name: Create release

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

permissions:
  contents: write  # Ensure write permissions

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository to access its contents

      - name: Debug GitHub context
        run: |
          echo "GitHub repository: $GITHUB_REPOSITORY"
          echo "GitHub event: $GITHUB_EVENT_NAME"
          echo "GitHub ref: $GITHUB_REF"
          echo "Tag name: ${{ github.ref_name }}"

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          # Remove leading 'refs/tags/' from the tag name
          tag_name=$(echo "$tag" | sed 's/refs\/tags\///')
          
          # Create the release using GitHub CLI (`gh`)
          gh release create "$tag_name" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag_name#v}" \
              --notes "Release notes for $tag_name"

